### ISSUE TITLE
Cpu usage

### ISSUE THREAD

**Issue by erikdubois** [KevinHivert/Conky-lua#1]
i enjoyed looking into your code, seeing what was possible via lua...
Since i am a novice not everything worked on my linux mint port.
i ended looking into it as i found out that working via lua it took about 6% cpu to get the information via lua...

Just informing you.

**Comment by KevinHivert** [comment]
Well, first of all thanks your feedback ;)
This conky is for an ArchLinux system so some parts are very specific, like :

    file = io.popen("yaourt -Qu | wc -l | tail")

I use the sensors command to get my cpu temperature and that part is also be specific to my system. The network interfaces (wlp8s0 and enp7s0) are also specific to Arch, so you have to change them in order to run this conky on Mint.

For the cpu usage, on my laptop the cpu use is under 1%, but you can try to increase the interval update (in the conky-scripts/main-conkyrc file) to reduce your cpu load.

**Comment by erikdubois** [comment]
that was one of the issues
file = io.popen("yaourt -Qu | wc -l | tail")

my alternative would be 
aptitude search "~U" | wc -l | tail

copy/pasting it in was an explosion in cpu usage.
Every second it went to ask if there were updates

tried to make a parse command so that it would do execi 6300 or so... Had to change to code so much,  i eventually gave up.

If i could make lua to skip this specific command line for x number of times that would help.

I have to find a work around in that regard
nevertheless I will work on it again once i have more lua knowledge.

I did a replace for my eth0 and wlan0 - worked just fine.

did the interval update to 4 sec... but that's not the solution. 
Clock skips seconds... it seems like it is crashing.

**Comment by KevinHivert** [comment]
For the updates a counter should do the trick :

    local counter = 0
    local file = io.popen("aptitude search "~U" | wc -l | tail")
    local output = file:read("*a")
    file:close()
    local start, finish, updates = string.find(output,"(%d+)")

At the start of the document, before the line : function conky_main().
In that way, variables updates and counter are initiated.

Then when you want to update the updates value:

    counter = counter + 1
    if (counter = 6300) {
        file = io.popen("aptitude search "~U" | wc -l | tail")
        output = file:read("*a")
        file:close()
        start, finish, updates = string.find(output,"(%d+)")
        counter = 0
    }

So you check update all 6300 execution, that mean all 6300 * update_interval seconds.

**Comment by erikdubois** [comment]
Looks good

Verstuurd vanaf mijn iPhone
